name: Prueba de Comunicacion Asus

on:
  push:
    branches:
      - main 

jobs:
  saludar-desde-asus:
    runs-on: self-hosted # Como solo tienes un espía, esto es suficiente por ahora

    steps:
      - name: El espía reportándose
        run: |
          echo "========================================="
          echo "¡Misión exitosa, Jefe!"
          echo "Estoy ejecutando esto desde la Asus con Ubuntu Server"
          echo "Mi usuario actual es: $(whoami)"
          echo "Mi sistema es: $(uname -a)"
          echo "========================================="