name: Despliegue Automatico SOLV

on:
  push:
    branches:
      - feature/pruebas-runner 

jobs:
  desplegar-en-asus:
    runs-on: self-hosted

    steps:
      - name: Descargar el código más reciente
        uses: actions/checkout@v4

      - name: Construir y Levantar SOLV con Docker Compose
        run: |
          docker compose down
          docker compose up -d --build